Homework 1
kosandron/java-course-2023 pull request #1
Opened 2023-10-05 16:24 UTC by kosandron

2023-10-05 21:49 UTC, Stasik371 requested changes

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +    private Task0() { }
Лучше пропустить строку сверху

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Есть душная спецификация, что правильно писать 
```
private static final Logger LOGGER = LogManager.getLogger();
```
Давай исправим)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +            if (Character.isDigit(str.charAt(i))) {
Какая-то очень большая и страшная конструкция, давай может валидацию до самой логики? А лучше в отдельный метод

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +
Лучше убрать пропуск строки

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +
и тут

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +    private Task2() { }
Кликай иногда ctrl+alt+L)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +            if (a[i] < aMin) {
Есть метод ```Collections.max``` / ```Collections.min()``` Мне кажется с ними будет удобнее и читаемее)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +        StringBuffer buffer = new StringBuffer(str);
А почему решил использовать StringBuffer?) Советую почитать статейку и узнать в чем разница со StringBuilder https://javarush.com/groups/posts/2351-znakomstvo-so-string-stringbuffer-i-stringbuilder-v-java

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +        for (int i = 0; i < str.length() - 1; i += 2) {
Кажется, что красивее и быстрее будет сделать за 1 проход

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +        int k = power;
Немного непонятно: что такое k В продуктовой разработке мы чаще читаем код, чем пишем, поэтому предлагаю называть переменные, методы и классы чуть более осознанно)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    public static int binpow(int value, int power) {
Давай придерживаться camelCase, лучше назвать binPow

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    public static int countDigits(int value) {
Немного забежим вперед, все методы(кроме isPalindromeDescendant) лучше сделать private. Другие классы должны уметь вызывать только метод проверки на палиндром, а о его реализации(какие он методы внутри дергает) знать не должны)

Такое нужно сделать во всех классах. И тестировать только public методы

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +        int delitel = binpow(10, length - 1);
Лучше не называть транслитом)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    public static int countDigits(int value) {
И еще поинт: Ты уже писал такой метод, в принципе можно переиспользовать, если ты уверен, что он подойдет)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        while (number != 6174) {
Думаю, что такое лучше в константу вынести)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        for (int i = 0; i < digitCount.length; i++) {
Такой фор не нужен, все элементы по дефолту будут равны 0)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +    public static int countK(int value) {
В задании есть условие ```в котором не все цифры одинаковы```. Давай это отлавливать, а еще тест на это напишем

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateLeft(int value, int step) {
Кажется перемудрил) Можно попробовать через строку, так, возможно будет легче. Но по твоему усмотрению

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task8.java
> +    public static final int CELLINROWCOUNT = 8;
по спецификации константы должны писаться капсом и snake_case 

```suggestion
    public final static int CELL_IN_ROW_COUNT = 8;
```

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +            .isEqualTo(1023);
Не очень понятно, как ты получил 1023) Возможно стоит написать 17*60+3

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        String str = "9:12";
А вот это кстати невалидный формат)

Должно быть 09:12, а на это кидаться -1)

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        String str = "0:59";
тут тоже, должно быть 00

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Корректный тест 1")
Не нужно писать Корректный или некорректный) В DisplayName нужна такая информация, чтоб, посмотрев на нее-поняь что происходит в тесте) Также и с названием метода:

Можно как-нибудь так
 @DisplayName("Количество минут и секунд < 60")
void minutesToSeconds_shouldConvertToSecondsIfDataIsValis()

Понимаю, что громоздко, но на сложных тестах будет легче)

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Корректный тест 1")
Так нужно сделать со всеми тестами...

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        if (value == 0) {
Ты сделал отдельную проверку на ноль, почему бы не написать тест)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        if (value == 0) {
А еще кстати бывает -0)

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +}
В целом лайк, все ТестКейсы учтены. Нужно только формат поправить на MM:ss

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    void SuccessTest1() {
Названия методов с маленькой буквы

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task4Test.java
> +}
Можно добавить тестик на пустую строку

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +public class Task6Test {
Если честно, то выглядит так, будто тесты ничем не подкреплены) Это ни в коем случае не камень в твой огород, просто хочется, что проверки чем-то подкреплялись... Возможно стоит комментарием посчитать ручками, но с другой стороны - это задачка такая, никак по-другому не сделаешь

2023-10-05 21:49 UTC, Stasik371 commented on src/test/java/edu/hw1/Task8Test.java
> +}
Давай добавим граничные случаи: 
    1. Когда на доске все кони
    2. Когда на доске ни 1 коня
    3. Когда на доске 1 конь

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        for (int i = 0; i < str.length(); i++) {
Почитай про функцию класса String .split() Возможно она поможет)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds > 59 || !delimetr) {
Можно не делать answer -1, а сразу return -1)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds > 59 || !delimetr) {
Так мы не будем заходить в ненужные нам блоки кода, а сразу выйдем из метода

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +            if (Character.isDigit(str.charAt(i))) {
Возможно стоит проверить такой кейс "-01:10"

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    public static boolean isPalindromeDescendant(int value) {
Кажется, что можно проще) Если придумаешь, как сделать меньше циклов, то будет круто)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +    public static int sortNumber(int value) {
Можно кстати строки(а точнее массив char-ов) сортировать) Так возможно проще будет, чем велосипед с дополнительным затратами по памяти придумывать)

2023-10-05 21:49 UTC, Stasik371 commented on src/main/java/edu/hw1/Task8.java
> +                if (field[i][j] == 1 && checkNeither(i, j, field)) {
У тебя тут n\*\*4 Давай за n\*\*2

2023-10-06 08:09 UTC, kosandron commented on src/main/java/edu/hw1/Task4.java
> +        StringBuffer buffer = new StringBuffer(str);
StringBuffer потокобезопасен, поэтому решил использовать. Мы же не знаем, в какой программе наш метод будет применяться.

2023-10-06 08:11 UTC, kosandron commented on src/main/java/edu/hw1/Task3.java
> +            if (a[i] < aMin) {
Знаю про них, не работают на обычных массивах. Переделать массив в коллекцию Array?

2023-10-06 08:27 UTC, kosandron commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds > 59 || !delimetr) {
у меня была там проблема, что анализотар не позволял больше 4 ретурнов, сейчас решил это

2023-10-06 08:28 UTC, kosandron commented on src/main/java/edu/hw1/Task1.java
> +            if (Character.isDigit(str.charAt(i))) {
'-' - непозволительный символ, упадет на валидации, но тест напишу

2023-10-06 12:18 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +            if (a[i] < aMin) {
Глаз вчера ночью замылился) Оставляй так)

2023-10-07 17:07 UTC, kosandron commented on src/main/java/edu/hw1/Task6.java
> +    public static int sortNumber(int value) {
а вот тут вопрос, где мы больше памяти потратим: в простом массивчике из 10 интов + 2 переменных инта или с кучей конвертаций к new Integer(), new String(), StringBuffer вылезит и сортировкой за O(nlogn) + там еще память уйдет.

2023-10-07 17:19 UTC, kosandron commented on src/main/java/edu/hw1/Task8.java
> +                if (field[i][j] == 1 && checkNeither(i, j, field)) {
Нет тут n^2. Все ограничено константами, O(1).

2023-10-08 12:48 UTC, Stasik371 commented on src/main/java/edu/hw1/Task8.java
> +                if (field[i][j] == 1 && checkNeither(i, j, field)) {
Ой, вообще согласен, шахматные поля вроде увеличиваться не планируют) Я скорее про то, что можно решить за 2 вложенных цикла, а не за 4) Внутри же вызывается еще ``checkNeither()``

2023-10-08 12:52 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +        StringBuffer buffer = new StringBuffer(str);
Тут больше коммент, чтоб ты понял в чем разница) Вообще для простых задачек на алгосы о многопоточности можно не париться) У нас вроде будет отдельный модуль про всю эту историю

2023-10-08 12:56 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +        StringBuilder buffer = new StringBuilder(str);
Объект типа StringBuilder, а называется buffer) Что-то неладное))

2023-10-08 12:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Test 1: normal time")
Можно не писать номер теста, они все равно могут запускаться в разном порядке)

2023-10-08 13:00 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    void normal_time_test1() {
Вообще, лучше не писать snake_case-ом методы, про method_shouldDoSmth это скорее исключение. Поправь в следующем мре или в этом)

2023-10-08 13:03 UTC, Stasik371 commented
Вроде все ок, осталось поменять названия методов тестов. Прости за душноту, хочется, чтоб ты сразу к хорошему привык)

2023-10-08 17:37 UTC, kosandron commented on src/test/java/edu/hw1/Task1Test.java
> +    void normal_time_test1() {
Писать camel  casом в тестах тогда?

2023-10-08 17:39 UTC, kosandron commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Test 1: normal time")
А как лучше разделять тесты с однотипными данными, подходящими к 1 случаю? Или лучше 1 случай - 1 тест?

2023-10-08 17:40 UTC, kosandron commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Test 1: normal time")
В джаве есть что-то подобное inline тестам?

2023-10-15 17:42 UTC, Stasik371 commented
Ты в следующий раз отписывай на EDU, а то потеряю)

2023-10-15 18:15 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    void normal_time_test1() {
Ага

2023-10-15 18:17 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Test 1: normal time")
Да, 1 случай=1 ТК


Немного не понял про inline тесты... Если ты про плюсы, то нет) Если ты про котлин, то тоже нет)

2023-10-16 12:38 UTC, merged